### ISSUE TITLE
Please add the support for TrHologram

### ISSUE THREAD

**Issue by ahdg6** [Rosewood-Development/RoseStacker#10]
Please add hologram handler for [TrHologram](https://www.spigotmc.org/resources/trhologram-1-8-1-15.75503/)
It's a packet-based hologram plugin,I think It would be a practical feature if you add the support for it.
Sincerely hoping you can consider it,thank you.
github:[https://github.com/Arasple/TrHologram](https://github.com/Arasple/TrHologram)
doc:[https://trhologram.trixey.cn/api/usage](https://trhologram.trixey.cn/api/usage)

**Comment by Esophose** [comment]
Unfortunately it looks like that plugin is currently inactive. If it becomes active again and supports 1.16.4, I'll add support for it.

**Comment by ahdg6** [comment]
This plugin is still working on 1.16.4.
and the developer of it is developing another premium plugin called TrMenu that meant TrHologram is still being supported,but without further feature being developed.

**Comment by Esophose** [comment]
It does not support 1.16.4 or any version of 1.16, I know this because I tested it myself [https://prnt.sc/vqa58q](https://prnt.sc/vqa58q). After letting the server load for over 5 minutes while that plugin downloaded dependencies, it then just errored on startup and failed to load.

**Comment by ahdg6** [comment]
Taboolib:https://github.com/TabooLib/TabooLib
You need to get dependence from here to load it,It must be put on the libs file which in the root path of server 

./libs/TabooLib.jar
![Screenshot_20201126_140304](https://user-images.githubusercontent.com/36436808/100314617-fe991080-2ff1-11eb-9b1d-3414d1c35cbd.jpg)

Thank you for your patience.

**Comment by Esophose** [comment]
I already have that there though. Here's my startup log if you don't believe me
[latest.log](https://github.com/Rosewood-Development/RoseStacker/files/5600865/latest.log)

**Comment by ahdg6** [comment]
I'm sorry to reply so late.
I have no idea why it can't be loaded for you,but It's still working on my 1.16.4 Paper Server.
Try to use this to replace the Taboolib.jar:https://1drv.ms/u/s!Asmkq8Fp9qN-grwsUswmiuqgmmsAZg

**Comment by Skiller9090** [comment]
![image](https://user-images.githubusercontent.com/37740659/103711340-1e3b3580-4faf-11eb-9250-041396f96fd5.png)
TrHologram does appear to still be working in 1.16.4 paper-332 as shown above

**Comment by Esophose** [comment]
I just tried re-downloading it again and still can't get it to work on 1.16.4 using paper-391. I just get a several separate errors. Here is my startup log for proof: https://pastebin.com/2hFJ1nz1
I've tried using the latest versions on both Spigot and GitHub, neither work.

**Comment by Esophose** [comment]
Okay I stand corrected. After deleting libs/TabooLib.jar, deleting the plugins/TabooLib folder, and downgrading to Java 8 only then did it finally work. I had to jump through so many random hoops to get that working, ugh.

**Comment by Esophose** [comment]
@Skiller9090 @ahdg6 I can't get the commands working, all it does is throw errors. Can you give me some example commands to run just to create a hologram with the text `Test`? Everything I try to do with this plugin just ends up giving me trouble.

**Comment by Skiller9090** [comment]
Will do when i get up out of bed in 7 hours, if you want @Esophose i can program the hologramHandler for the plugin for you

**Comment by Esophose** [comment]
I'm fine with adding it myself as it's pretty much an identical process to the other ones, I just have no idea why this plugin is giving me so much trouble with commands and such. I'll implement it real quick and report back on if it works or not.

**Comment by Esophose** [comment]
If one of you could test this jar and send a screenshot of the hologram if it works that would be great. It's still refusing to create any holograms on my server and is just giving me errors.

Commit: 7e5862ea75b1c544e55bd7a2d8028f408557199f
Jar: [RoseStacker-1.1.5.zip](https://github.com/Rosewood-Development/RoseStacker/files/5773292/RoseStacker-1.1.5.zip)

**Comment by Skiller9090** [comment]
alright ill give a test

**Comment by Skiller9090** [comment]
![image](https://user-images.githubusercontent.com/37740659/103748111-89125e00-4ffb-11eb-8196-c25aa1b795fc.png)
Good start
![image](https://user-images.githubusercontent.com/37740659/103748173-9d565b00-4ffb-11eb-9a74-08ecc2600572.png)
it is working all good
![image](https://user-images.githubusercontent.com/37740659/103748195-a5ae9600-4ffb-11eb-9357-1c77277c3de8.png)
No lingering either perfection :)

**Comment by Esophose** [comment]
The holograms are only used for stacked spawners and blocks, the entities and items just use the nametags. Try placing a stacked spawner and block to see if the hologram support worked.

**Comment by Skiller9090** [comment]
alright:
![image](https://user-images.githubusercontent.com/37740659/103748369-ead2c800-4ffb-11eb-886b-e2dddf793c07.png)

**Comment by Skiller9090** [comment]
![image](https://user-images.githubusercontent.com/37740659/103748406-f7572080-4ffb-11eb-86ed-a5bb7269e395.png)
Getting no errors in console either

**Comment by Skiller9090** [comment]
![image](https://user-images.githubusercontent.com/37740659/103748429-03db7900-4ffc-11eb-8451-2ddd6c126eee.png)
after deletion there is no lingering

**Comment by Esophose** [comment]
Needs to be moved down by half a block I guess but other than that looks good

**Comment by Skiller9090** [comment]
yep well done 👍

**Comment by Esophose** [comment]
Are you able to contact me on discord so I can just continue messaging you there? Nicole#0001

**Comment by Esophose** [comment]
TrHologram support has been added and will be in the next update.

**Comment by Skiller9090** [comment]
@ahdg6 Here is the beta version working with TrHolograms if you still need it!
[RoseStacker-1.1.5.zip](https://github.com/Rosewood-Development/RoseStacker/files/5774763/RoseStacker-1.1.5.zip)
