### ISSUE TITLE
Bug when kill > 100 creatures

### ISSUE THREAD

**Issue by NoltoxGit** [Rosewood-Development/RoseStacker#101]
Hello,
A player has just reported to me that sometimes, when he kills stacked creatures > 100, after a certain (random) move, they are all killed at once.

## Here is all the information about the server:
**Version:**
`Current: git-Purpur-2148 (MC: 1.20.4)*`

**Plugin version:**
`RoseStacker version 1.5.17 (latest dev build on Jenkins)`

**Config of the plugin:**
Pastebin: https://pastebin.com/WCBVAvD4

## Video for demonstrate the bug:

https://github.com/Rosewood-Development/RoseStacker/assets/75265787/1dd4065b-a38f-4a36-824d-a864f9c95816

**Comment by Esophose** [comment]
This is a known issue that we have known about for quite some time but it happens extremely rarely and we haven't been able to reliably reproduce it, so we haven't been able to fix it. I have never been able to reproduce this issue locally, if you manage to figure out how to actually reproduce it please let us know.

**Comment by NoltoxGit** [comment]
> This is an issue that we have known about for quite some time but it happens extremely rarely and we haven't been able to reliably reproduce it, so we haven't been able to fix it. I have never been able to reproduce this issue locally, if you manage to figure out how to actually reproduce it please let us know.

Ty for your reply,
From our several tests, it happens to us many times, just take a big stack of mob and type

**Comment by NoltoxGit** [comment]
Fixed in this commit https://github.com/Rosewood-Development/RoseStacker/commit/7e914e3ff9b2a735b4cadecfe92ad93f5fe2baad.
Thank you so much !
