### ISSUE TITLE
PreDropStackedItemsEvent not firing

### ISSUE THREAD

**Issue by GeorgeV220** [Rosewood-Development/RoseStacker#111]
Hello!

I'd like to propose an enhancement: the addition of a `StackedItemSpawnEvent`. 
Here's the rundown:

**Purpose:**
- When a stacked item is set to spawn in the world, this event would trigger.
- Developers would have the option to intervene and prevent the item from spawning by handling this event. This could be useful for situations where specific spawning conditions need to be met or just straight up cancelling the event for other things.
- Additionally, developers could modify aspects of the item, such as the amount and type of item being spawned.

Looking forward to your thoughts on this!

**Comment by Esophose** [comment]
This one? https://github.com/Rosewood-Development/RoseStacker/blob/master/Plugin/src/main/java/dev/rosewood/rosestacker/event/PreDropStackedItemsEvent.java

**Comment by GeorgeV220** [comment]
OMG I had not noticed this event, I'm sorry. Thank you very much!!

**Comment by GeorgeV220** [comment]
Hello again,
I'm reopening the issue because `PreDropStackedItemsEvent` is not being fired at all. When listening to this event, no console output appears when I drop stacked items or spawn them with commands. The listener is registered using Bukkit.

```java
@EventHandler
public void onStackSpawnEvent(PreDropStackedItemsEvent event) {
    Bukkit.getLogger().info("test");
    Bukkit.getLogger().info(event.getItems().toString());
}
```

RoseStacker version: 1.5.20
Server version: git-Purpur-2176 (MC: 1.20.4)

**Comment by Esophose** [comment]
The event only fires when stacks larger than 64 are being dropped by rosestacker all at once. If you want to be able to detect all items dropping you should also listen to the EntitySpawnEvent for item spawns like normal
