### ISSUE TITLE
Accessing stacked amount

### ISSUE THREAD

**Issue by deadspidervenom** [Rosewood-Development/RoseStacker#116]
how would i access the stack amount via another mod like "levelledmobs" for use in the name display. As your name display conflicts with theirs.

**Comment by Esophose** [comment]
There isn't currently any way to do that, the two plugins are incompatible as they both try to modify the nametags.

**Comment by deadspidervenom** [comment]
from my understanding levelledmobs is able to access the metadata or PDC of a plugin, then use the data in its nametag and you are able to do so manually.

if rosestacker uses NBT data storage for its stacked amount, it should be able to access it via this route. and display it.

**Comment by deadspidervenom** [comment]
Perhaps this would be easier to just PlaceholderAPI support, since levelledmobs and other such plugins have it as well. Something like

%stackcountmob%
%stackcountitem%
%stackcountspawner%

**Comment by Esophose** [comment]
Placeholders cannot be parsed for mobs, only players.

**Comment by deadspidervenom** [comment]
Huh but ive seen hologram mob healthbars that have placeholderapi compatibility, or am i mistaking the usage of that compatibility.

**Comment by Esophose** [comment]
Those other plugins are likely adding the placeholders themselves, of which I would have no power to modify on my own. Something I could do is add support for the levelledmobs level in the RoseStacker mob name tag, but adding RoseStacker's stack count to another plugin's nametag would have to be implemented by that other plugin, PlaceholderAPI does not have any sort of capability of being used for mobs. If exposing the levelledmobs level to the RoseStacker mob name tag is something that could be useful for you, I could turn this into a feature request instead.

**Comment by deadspidervenom** [comment]
(i apologize if this i am misunderstanding this)

So if instead of giving it to placeholderapi about about the opposite? Letting placeholderapi stuff being used in your holograms or is that already a thing? I pretty new to the placeholderAPI stuff i apologize.
