### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by LuluxClient** [Rosewood-Development/RoseStacker#124]
After reviewing a spark I found out that Rose was taking a lot for nothing and that it needs to avoid the stream api usage as it's creating copies on memory 

![image](https://github.com/user-attachments/assets/757bbb8b-8fe9-41c6-8224-4c7b365098c9)

**Comment by Esophose** [comment]
Please post a full spark link

**Comment by LuluxClient** [comment]
> Please post a full spark link

I do not wish to share my spark, can I DM you it on discord ?

**Comment by Esophose** [comment]
f8179fcabe15907549e2704b35f099b2179b8a63
