### ISSUE TITLE
Could not pass event SheepRegrowWoolEvent

### ISSUE THREAD

**Issue by leogianfagna** [Rosewood-Development/RoseStacker#125]
https://mclo.gs/zClnG03

RoseStacker v1.5.27
purpur 1.21.1

Keep spamming time to time, even if there is not player activity.

**Comment by leogianfagna** [comment]
Updated to 1.5.30. Still bugged

**Comment by Esophose** [comment]
This looks like a configuration error. The sheep regrow wool amount value is formatted like `25` and needs to be formatted like `25.0` to work, for example. That setting would be in the entity_settings.yml file

**Comment by leogianfagna** [comment]
> This looks like a configuration error. The sheep regrow wool amount value is formatted like `25` and needs to be formatted like `25.0` to work, for example. That setting would be in the entity_settings.yml file

thanks for information
