### ISSUE TITLE
(BUG) Custom Item Display-Tags are not working on **1.21+**

### ISSUE THREAD

**Issue by Ixoenicbolt** [Rosewood-Development/RoseStacker#126]
Custom item display-tags/names do not work as of 1.21+

![bugreport](https://github.com/user-attachments/assets/371d28bc-24a3-4931-b6f3-e86c6b50641e)

**Comment by Esophose** [comment]
RoseStacker just displays whatever is saved as the item's display name. I'm guessing that plugin is perhaps setting some component that RoseStacker does not currently support. What plugin is that?

**Comment by Ixoenicbolt** [comment]
We are currently using the latest version of Oraxen. The display names worked fine on 1.20, but not 1.21.
*(1.20 was a typo in the title)

**Comment by Esophose** [comment]
I'm almost certain this is related to Oraxen using a different component for the item name than RoseStacker is expecting. I don't currently see any Spigot API for getting the exact display name component, I'm looking into it though

**Comment by Esophose** [comment]
Good news I've figured out how to fix this and can get a fix pushed later today

**Comment by Esophose** [comment]
Can you give this jar a try and see if it works? 2ef56c9b14bf641d69f58c3f6f7a23b4925de512 https://jenkins.rosewooddev.io/job/Rosewood%20Development/job/RoseStacker/241/artifact/build/libs/RoseStacker-1.5.28.jar

**Comment by Ixoenicbolt** [comment]
![image](https://github.com/user-attachments/assets/aa9d34b1-3352-490c-af3a-eff0a177506d)

Definitely works on my end now

**Comment by Esophose** [comment]
Sweet, I'll get that pushed to Spigot soon
