### ISSUE TITLE
Add the possibility to disable AI from all mobs

### ISSUE THREAD

**Issue by Typheonn** [Rosewood-Development/RoseStacker#18]
Hi,

I wanted to know if you could add the possibility to disable the AI from all mob one by one (in the entity_settings,yml) ?

**Comment by Esophose** [comment]
That is already possible from in the `spawner_settings.yml` file. You can change the value from `default` to `true` to disable the AI for specific mobs. Note that the AI will only be disabled from mobs spawned from spawners.

**Comment by Typheonn** [comment]
Yes, but is it possible to make that for all mobs, even if they don't spawn from spawner ?

**Comment by Esophose** [comment]
No that is not currently possible
