### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Dreeam-qwq** [Rosewood-Development/RoseStacker#19]
Hi, I like your plugin that is very useful. However, I can't load RoseStacker after I update the Viaversion and other plugins.

Error paste:
https://paste.gg/p/anonymous/89bc92756e7a4f559b5ced53cc3f0e8e

Environment:
Purpur 1.16.5

plugins:
RoseStacker v1.2.4
Viaversion build #504
Viabackwards build #303
Viarewind build #211

**Comment by Esophose** [comment]
Can not reproduce, used the same versions on Purpur and it loads fine. Try redownloading the latest [ViaVersion jar](https://ci.viaversion.com/job/ViaVersion/506/).

**Comment by Dreeam-qwq** [comment]
> 
> 
> Can not reproduce, used the same versions on Purpur and it loads fine. Try redownloading the latest [ViaVersion jar](https://ci.viaversion.com/job/ViaVersion/506/).

sorry, I forgot to tell you. I used the latest dev builds of the the Via.

**Comment by Esophose** [comment]
Fixed, here's a build if you need it now. It wont' be released until v1.2.5, not sure when that will be.
[RoseStacker-1.2.4.zip](https://github.com/Rosewood-Development/RoseStacker/files/6437429/RoseStacker-1.2.4.zip)
