### ISSUE TITLE
[Request] some config option additions and changes

### ISSUE THREAD

**Issue by Nubebuster** [Rosewood-Development/RoseStacker#21]
Entities currently always insta-stack from a spawner. This is great for performance (I presume) but I like the entities to spawn seperately and then merge when they get into my desired stacking range. Could you add an option to set insta-stack true or false for spawners too like you have in global-entity-settings (which I presume to be only for natural spawning) ?

Could you make an option for making spawn-max-nearby-entities take stacked mobs into account? Otherwise I will have to set it to 1

PS I appreciate the previous additions. They were precisely what I wanted!

**Comment by Esophose** [comment]
I thought both of those settings already existed but it turns out neither of them actually do. They should be pretty simple to add.

**Comment by Nubebuster** [comment]
Also an unrelated question
> /give nubebuster spawner{display:{Name:'[{"text":"Cat Spawner","italic":false,"color":"gray"}]'}} 1
gives me a cat spawner that works with your plugin. But it does not stack with spawners using the /rs give 

Should I care about the item difference and what is the difference?

**Comment by Esophose** [comment]
The spawner referenced in that give command doesn't have the entity type stored on it, all you did was rename it. If you properly include the entity type NBT on it then it should stack with other spawners properly. The way it is now RoseStacker and Minecraft itself will see it as a pig spawner.

**Comment by Esophose** [comment]
Added in 7634c76396d0e90c77ec28b625fcef5e9c9f2ba0
