### ISSUE TITLE
DiceFurniture Plugin Support

### ISSUE THREAD

**Issue by tyepavitt** [Rosewood-Development/RoseStacker#25]
Please could you add support for the Dicefurniture plugin: https://www.spigotmc.org/resources/dicefurniture-plugin-m%C3%B6bel-plugin.6006/

Because at the moment, if you try and place a piece of furniture it spawns the mob instead.

**Comment by Esophose** [comment]
Cannot reproduce, the latest version of DiceFurniture works fine with RoseStacker. The eggs work as intended for me.
