### ISSUE TITLE
JavaDocs for API usage

### ISSUE THREAD

**Issue by tastybento** [Rosewood-Development/RoseStacker#26]
Hi,

I'm trying to use your API and it would be really useful if you could generate JavaDocs and deploy them to your Nexus server so that I could understand what the various methods do. I don't know how to do it via Gradle, but with Maven it's pretty straight forward. I know the API is just one class, and I can look at the source here on GitHub, but it just makes it a bit easier to program when your IDE pops up the JavaDoc for the various methods.

Thanks in advance!

**Comment by Esophose** [comment]
I'll get them pushed out tomorrow night, I've been meaning to for a while but just wasn't sure how to do it for Gradle projects with multiple modules. I'm sure I can figure something out though.

**Comment by Esophose** [comment]
Couldn't figure this out for the life of me, I don't know how to use Gradle as well as I'd like. Just going to close this.
