### ISSUE TITLE
Allow all Items to stack and have Items stack in inventory upon pickup.

### ISSUE THREAD

**Issue by SirCraftypants** [Rosewood-Development/RoseStacker#3]
Hi, love Rosestacker but, is there any chance you can allow usually non stacking items like Water Bucket and Potion, stackable. I used another plugin for stacking these items and although it does the job, it's a bit buggy.

Also allow for Items to properly stack upon pickup <- this is the Bug that the other stacking plugin has. It only allows for x2 item to stack upon pickup, the rest fill individual slots.

If Rosestacker was able to do this then it would be the first to do so i believe and it would allow me to only have one stacking plugin, that would be awesome.

**Comment by Esophose** [comment]
Sounds like a good feature to add, thanks for the suggestion
