### ISSUE TITLE
RoseStacker - CloudCollectors and JetMinions Crash Server

### ISSUE THREAD

**Issue by brasilcraft54** [Rosewood-Development/RoseStacker#30]
rosestacker is taking down tps and server with jetminions or cloucollectors see the videos below.
if I remove the rosestacker the problem ends but I like the rosestacker so much I would like you to fix it please

Server Version: Purpur-1.17.1 last version

plugin version: 1.3.0

1° https://www.youtube.com/watch?v=cU3zNHJWRks

2° https://www.youtube.com/watch?v=m6mW0tGrxD8

3° https://timings.aikar.co/?id=6c801f45b5bd457fb42a60ac9f7bae7d

**Comment by brasilcraft54** [comment]
I managed to replicate the bug with 50k of creepers, let's say that the player has 10 spawners and leaves accumulating the creper up to 50k for example and kills it knocks down any server.

https://www.youtube.com/watch?v=inJOxSMoTOw

**Comment by brasilcraft54** [comment]
I was able to replicate even myself without minions and collector

1° https://www.youtube.com/watch?v=6JHEssZHJW0

**Comment by Esophose** [comment]
Please send your config.yml. It looks like you have `trigger-death-event-for-entire-stack-kill` enabled which will 100% cause lag like that to happen if you have stacks that large.

**Comment by brasilcraft54** [comment]
https://pastebin.com/7SEYCnpm

**Comment by Esophose** [comment]
Please set `death-event-trigger-async` to true and see if that helps.

**Comment by brasilcraft54** [comment]
> death-event-trigger-async

will this solve the lag issue?

**Comment by PatrikX23** [comment]
> > death-event-trigger-async
> 
> will this solve the lag issue?

I also had this issue its solved for me try it

**Comment by brasilcraft54** [comment]
> > > death-event-trigger-async
> > 
> > 
> > will this solve the lag issue?
> 
> I also had this issue its solved for me try it

![6766767676767](https://user-images.githubusercontent.com/67756407/129799250-06944562-1f91-4f98-92fd-509a95241dcf.PNG)
didn't solve for me

**Comment by brasilcraft54** [comment]
I tested it with the wildstacker and didn't have the same problem.

1° https://www.youtube.com/watch?v=TCKN8nDimlU

**Comment by brasilcraft54** [comment]
it's a shame that I have to leave the rosestacker because of problems, since in the wildstacker I don't have this problem. I just invoked 400k of mobs and I didn't even give 1 lag.

**Comment by brasilcraft54** [comment]
[ERROR] .... java.base@16.0.1/java.util.AbstractCollection.toArray(Unknown Source)

[ERROR] .... java.base@16.0.1/java.util.ArrayList.<init>(Unknown Source)

[ERROR] .... app//com.google.common.collect.Lists.newArrayList(Lists.java:149)

[ERROR] .... app//net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:805)

[ERROR] .... app//net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:726)

[ERROR] .... app//net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:555)

[ERROR] .... app//net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1553)

[ERROR] .... app//net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479)

[ERROR] .... app//net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406)

[ERROR] .... app//net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188)

[ERROR] .... app//net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)

[ERROR] .... app//net.minecraft.server.MinecraftServer$$Lambda$3658/0x0000000801390478.run(Unknown Source)

[ERROR] .... java.base@16.0.1/java.lang.Thread.run(Unknown Source)

[ERROR] .... ------------------------------

[ERROR] .... --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---

[ERROR] .... ------------------------------

[WARNING] .... Can't keep up! Is the server overloaded? Running 203828ms or 4076 ticks behind

**Comment by Esophose** [comment]
The two plugins don't treat large numbers of mobs the same, they aren't designed to be carbon copies of each other. RoseStacker accurately stacks mobs together and wasn't designed to be used with massive stack sizes like that. When you spawn 50k mobs in RoseStacker, the server actually has to spawn 50k mobs into the world. WildStacker only spawns 1 but they will all be exact clones of each other. The two plugins are not comparable like that. Use whichever suits your use case the best.

**Comment by brasilcraft54** [comment]
> The two plugins don't treat large numbers of mobs the same, they aren't designed to be carbon copies of each other. RoseStacker accurately stacks mobs together and wasn't designed to be used with massive stack sizes like that. When you spawn 50k mobs in RoseStacker, the server actually has to spawn 50k mobs into the world. WildStacker only spawns 1 but they will all be exact clones of each other. The two plugins are not comparable like that. Use whichever suits your use case the best.

yes it's a shame I liked the rosestacker so much but I'm abandoning it because it's possible to crash any server with this plugin just let it group 50k mobs and kill and that's it.

**Comment by Esophose** [comment]
Not really sure what you mean by crash any server, mine can handle killing even 500k mobs with no lag issues. There are other server that have larger stack sizes and don't have that problem either. Are you sure you enabled the trigger death event async setting?
