### ISSUE TITLE
Error with IridiumSkyblock, incompatibility?

### ISSUE THREAD

**Issue by Strahilchu** [Rosewood-Development/RoseStacker#39]
Logs:
https://mclo.gs/5s3nBa5
and
https://mclo.gs/V3nulLy

Server: git-Paper-397 (MC: 1.17.1)
RoseStacker 1.4.0
IridiumSkyBlock: 3.2.2

Had crazy errors, these are some. Would appear anytime I did commands or talked in chat.
However after downgrading RoseStacker to v1.3.4 (the one before 1.4.0) the issue went away. 
This tells me the problem is somewhere with Rose or Iridium, I have opened an issue report on their github but want to let you guys know about this as well. 

Any help is appreciated!

**Comment by Esophose** [comment]
Known issue, is fixed in the latest IridiumSkyblock build. Will also be fixed in RoseStacker v1.4.1 which I'll have released soon.
