### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by LuluxClient** [Rosewood-Development/RoseStacker#42]
Rose stacker is taking 5% of my total server tick with 70 players online, it's a plugin that is supposed to reduce lag but it adds lags:
![image](https://user-images.githubusercontent.com/62576432/146686150-ae8862b8-115b-4c67-ae18-131ad75309a2.png)
https://spark.lucko.me/yaPBYCoKlS 

Server: purpur 1.17.1
Java: 16

**Comment by LuluxClient** [comment]
Rose stacker is now taking 12% of my server performance: 
https://spark.lucko.me/y1cUCa0ggL

**Comment by Billabomb75** [comment]
Look at what it is from Rose Stacker that causes issues... 

Like on my server at the moment I get a stacking issue. After a restart it was fine for a while

**Comment by Esophose** [comment]
These things should be fixed on the latest release, if they aren't contact me on my support discord server and I can send you the latest dev build. Make sure to set legacy-data-migration to false at the top of the config for a large performance boost if you haven't.
