### ISSUE TITLE
DecentHologram support

### ISSUE THREAD

**Issue by LuluxClient** [Rosewood-Development/RoseStacker#43]
Hey I was wondering if RoseStacker could add DecentHologram support. 
It has a lot of options and is a great alternative to Holographic Display and HoloExtension which is super performance heavy.
https://www.spigotmc.org/resources/decent-holograms-1-8-1-18-papi-support-no-dependencies.96927/

**Comment by Esophose** [comment]
The latest version of RoseStacker already supports DecentHolograms, have you tried it?

**Comment by LuluxClient** [comment]
> The latest version of RoseStacker already supports DecentHolograms, have you tried it?

I was just checking the wiki and I didn't really saw it

**Comment by Esophose** [comment]
Thanks for letting me know, I've gone ahead and updated the wiki.
