### ISSUE TITLE
BugReport: Magmacubes inflict damage to players when they are near them (with ai disabled)

### ISSUE THREAD

**Issue by TamrielNetwork** [Rosewood-Development/RoseStacker#46]
The title sais it all more or less. Also no errors in console. And other mobs work fine.

Paper Version: git-Paper-160 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 919e594)
RS Version: 1.4.2
Java Version: build 17.0.1+12-Debian-1deb11u2

**Comment by Esophose** [comment]
Forgot to mention but this should have been fixed in a somewhat recent update
