### ISSUE TITLE
Support for bedrock players

### ISSUE THREAD

**Issue by Trinchezito** [Rosewood-Development/RoseStacker#48]
Hi can you add support for unsage username? This will help for geysermc servers that support bedrock players. 
![image](https://user-images.githubusercontent.com/98068350/158494486-3fd8c61f-a53a-44c8-a82b-1a795684da50.png)

**Comment by Esophose** [comment]
This is added in the [command-system-rewrite](2384bef20bb3cb91e094f28167b5cd974559bb23) branch. Here's a download of that current branch. Please note that only the English locale currently supports the new command system and you will need to reset your en_US.lang file to get the new messages.
[RoseStacker-1.4.6-SNAPSHOT.zip](https://github.com/Rosewood-Development/RoseStacker/files/8258295/RoseStacker-1.4.6-SNAPSHOT.zip)

**Comment by emmanuelvlad** [comment]
> This is added in the [command-system-rewrite](https://github.com/Rosewood-Development/RoseStacker/commit/2384bef20bb3cb91e094f28167b5cd974559bb23) branch. Here's a download of that current branch. Please note that only the English locale currently supports the new command system and you will need to reset your en_US.lang file to get the new messages. [RoseStacker-1.4.6-SNAPSHOT.zip](https://github.com/Rosewood-Development/RoseStacker/files/8258295/RoseStacker-1.4.6-SNAPSHOT.zip)

Regression in 1.4.8

**Comment by Esophose** [comment]
These builds are available here: https://jenkins.rosewooddev.io/job/Rosewood%20Development/job/RoseStacker-CommandSystemRewrite/lastBuild/
