### ISSUE TITLE
Suggestion for IA (

### ISSUE THREAD

**Issue by D3BoxOfficiel** [Rosewood-Development/RoseStacker#49]
Make sure that you can whitist entities for AI, I explain myself when we deactivate the AI of all entities, to be able to selected those we want who remains activated like bees, WITHER, DRAGON or The Llama for the Pinata plugin.

At the same time added the whitist by worlds

**Comment by Esophose** [comment]
Mob AI can be disabled per entity type in the entity_settings.yml file. It's not going to be possible to change per world though.
