### ISSUE TITLE
Armor Stacking Can't be Disabled

### ISSUE THREAD

**Issue by Johandrex** [Rosewood-Development/RoseStacker#55]
See the configuration file and image down below. There's no "armor_stand" in the entity file.

RoseStacker v1.4.13
git-Paper-131 (MC: 1.19.2)

![2022-08-18_16 40 37](https://user-images.githubusercontent.com/8752172/185423591-a05efd59-ef82-45f2-8854-d98c751e35bf.png)

**Comment by Esophose** [comment]
Armor stands and players do not stack so there is no setting for them. I don't see any stacked armor stands in your image there

**Comment by Esophose** [comment]
Are you trying to enable armor stand stacking? That isn't something RoseStacker can do, armor stands cannot be stacked.

**Comment by Johandrex** [comment]
Correct, if anyone stumbles on this problem, set the following settings in your paper servers configuration files.

```
armor-stands:
    do-collision-entity-lookups: false
    tick: false
```
