### ISSUE TITLE
Support for SafariNet plugin

### ISSUE THREAD

**Issue by NicoNekoDev** [Rosewood-Development/RoseStacker#56]
Come to my attention that SafariNet doesn't really works great with your plugin.
1) The spawn eggs from SafariNet can change spawners. Please add an option to block changing the spawner with eggs.
2) If the mobs are stacked, the whole stacks gets catched in the net, but upon releasing the mob, no stack is found. Please change so you can only catch on mob at the time from the stack, and let the rest of the stack alive.
Here is the API for SafariNet: https://docs.spaceio.xyz/plugin/safarinet/api.html
Thank you!

**Comment by Esophose** [comment]
SafariNet added their own support to RoseStacker which allows picking up the entire stack. You should ask them about adding a setting to change that behavior, as I didn't add support for it. Also mention to them the egg thing, sounds like something on their end too.
