### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ItzZisker** [Rosewood-Development/RoseStacker#58]
wtf?????
![Screenshot_20220918_005724](https://user-images.githubusercontent.com/68909399/190875403-ff2abf58-b410-4882-960c-b0c694fa8689.png)

**Comment by ItzZisker** [comment]
16 million elements, ayo whatttttttt

**Comment by SwartZCoding** [comment]
@ItzZisker I saw you close your issue, how did you fix you issue ?

**Comment by Esophose** [comment]
> @ItzZisker I saw you close your issue, how did you fix you issue ?

This should be resolved in the latest v1.5.0+ updates. The only way it can still happen that I know of is if you have the Jobs plugin installed. The spawners hook it has tends to create memory leaks with marking mobs as spawned from spawners
