### ISSUE TITLE
Stacking of buckets

### ISSUE THREAD

**Issue by Fracticus** [Rosewood-Development/RoseStacker#66]
It is likely that 2 plugins are involved in causing this all to happen: this one and Sefiraat's Netheopoiesis (which gets water into the nether). All recordings are on the same server, there are no mods.

The food turning into buckets isn't consistent, but happens like this:

I start by putting the bread (someone else used beef) in the off hand by using f and plenty of space in my inventory. Then I just start clicking, no auto clicker involved. The food in the offhand is turns into buckets, where the amount of buckets is that of the stack of food. It was also noted that it only works when looking straight down at the block under the water. In many cases when one tries it, the water buckets start stacking.

The lagged stack of (water) buckets can be moved by dragging from slot to slot. It does fall partially apart when trying to add or take items from the stack. 

https://user-images.githubusercontent.com/102395700/195995771-ec9c0dae-b184-46d3-aff7-e50b5f468a24.mp4

![Schermafbeelding 2022-10-15 171430](https://user-images.githubusercontent.com/102395700/195995773-c41fac5c-bca3-478d-a7a7-d3fef6c87ca9.png)

https://user-images.githubusercontent.com/102395700/195995778-d8330442-c37a-4751-b3bc-e840b6a78570.mp4

https://user-images.githubusercontent.com/102395700/195995779-ef60b7bd-4e76-44a0-83e3-bae39d47f78c.mp4

If more info is required, let me know.

**Comment by Esophose** [comment]
Closing this as I don't see how RoseStacker is involved at all. RoseStacker doesn't interact with the player inventory and doesn't handle buckets picking up water like that
