### ISSUE TITLE
[SUGGESTION] Override spawner conditions

### ISSUE THREAD

**Issue by introvertism** [Rosewood-Development/RoseStacker#74]
I think it would be a nice feature to be able to override spawn conditions of specified mobs, for example making it so pigs don't need grass in order to spawn, or making it so iron golems/etc can spawn in mid air. Some other plugins have a similar feature and I'd love to see it here.

**Comment by Esophose** [comment]
This is already possible, please see the spawner_settings.yml file.

**Comment by introvertism** [comment]
> This is already possible, please see the spawner_settings.yml file.

I'm blind, thanks so much!
