### ISSUE TITLE
Feature-StackTool, important

### ISSUE THREAD

**Issue by diocan** [Rosewood-Development/RoseStacker#75]
Hi, I need to give access to users who buy the stack tool from the shop but unfortunately when you press shift-right-click on a spanwer it spawns the animals immediately,
what I ask is to add a way to be able to disable this function for users

**Comment by Esophose** [comment]
The stack tool is intended to be an admin tool. A player could accidentally mark an entire stack of entities unstackable and then fill your whole world with entities and crash. More functionality could be added to the stack tool in the future, it's just better to keep it out of players' hands.
