### ISSUE TITLE
StackedSpawnerPreSpawnEvent [Suggestion]

### ISSUE THREAD

**Issue by Hermelijn15** [Rosewood-Development/RoseStacker#76]
An event for the api that would fire whenever a spawner "triggers" and spawns a mobstack.

would be nice if we could:
get the entity (to get the location, type etc.)
can cancel it
can get and alter the amount of mobs

**Comment by Esophose** [comment]
https://github.com/Rosewood-Development/RoseStacker/blob/master/Plugin/src/main/java/dev/rosewood/rosestacker/event/PreStackedSpawnerSpawnEvent.java
