### ISSUE TITLE
Issues with SuperiorSkyBlock2

### ISSUE THREAD

**Issue by N1kyZ** [Rosewood-Development/RoseStacker#87]
Well, I already reported this problem to the SuperiorSkyblock2 DEV and he said that the problem could be RoseStacker :/
![image](https://github.com/Rosewood-Development/RoseStacker/assets/58773688/703dbfcd-963c-40f5-a410-389faa6139bb)

**Minecraft's Version**
This server is running Purpur version git-Purpur-1428 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9beb23b on ver/1.17.1)

**Plugin's Version**
SuperiorSkyblock2 version 2023.1-b22
RoseStacker version 1.5.7

**Describe the bug**
Monster/Animal Spawners are still spawning even with Spawner Monster Spawn settings
and Spawner Animals Spawn disabled

**To Reproduce**
Place some spawner on the ground
Disable monsters/animals spawning settings with spawners in /is settings

https://github.com/Rosewood-Development/RoseStacker/assets/58773688/593dc9c8-13bc-4278-933f-3ed8fc7fff49

☕

**Comment by Esophose** [comment]
There's a setting in the config.yml that's enabled by default to allow spawners to bypass region spawning rules. You can try disabling it and see if it does what you want, otherwise the two plugins may just be incompatible in that regard. The setting is called `bypass-region-spawning-rules`.

**Comment by N1kyZ** [comment]
It really worked, thank you :³
