### ISSUE TITLE
Slime Bug

### ISSUE THREAD

**Issue by Zsomi** [Rosewood-Development/RoseStacker#90]
If Slime spawner leidéz a normal sslim (big) then he will not throw a slimball if he throws a small one.

Steps:
1. Place a slimepawner.
2. Kill a big slime.
3. Enjoy the bug.

Server Version:  git-Purpur-1985 (MC: 1.19.4)*
Rosestacker verion: RoseStacker 1.5.8

**Comment by Esophose** [comment]
What's the issue here? Only the smallest slimes drop slimeballs, that's the vanilla behavior

**Comment by Zsomi** [comment]
Now I have another problem: if they stack the lazurite, gold etc. ore blocks they can't knock them out even I * rightly can't.
