### ISSUE TITLE
Server Crash (RS EntityData)

### ISSUE THREAD

**Issue by Zsomi** [Rosewood-Development/RoseStacker#93]
Server Version: 1.19.4-Purpur-1985
Plugin Version: 1.5.9

This is the crash log I got when the server would have restarted and instead it gave me a crash log. Supposedly not compatible with my server version.

https://pastebin.com/PXbzn4Tm

**Comment by Esophose** [comment]
Consider using SIMPLE entity data storage instead of NBT, this looks like a timeout during saving a very large entity stack.
